### PR TITLE
Update vulnerable libpng and minor nginx update

### PR DESCRIPTION
**Pull request by nberlee**

### CODE REVIEW

**Review by ashishk-1 — APPROVED** [review]
looks good to me

**Comment by oschaaf** [comment]
Thanks, this looks like a good idea.

**Comment by oschaaf** [comment]
@nberlee Since we don't have an automated CLA, I'm going to ask you manually, you are OK with us merging this and possibly upstreaming this later to the Apache licensed google/pagespeed repository?

**Comment by nberlee** [comment]
I am OK to have it later merged to the Apache licensed google/pagespeed

**Comment by oschaaf** [comment]
@nberlee thanks!

**Pull request merged**
